"""add drafts table, role category framing style, outreach draft link

Revision ID: 564bb6626f0a
Revises: 73bd7c86073a
Create Date: 2026-09-11 18:18:00.842126

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '564bb6626f0a'
down_revision: str | None = '73bd7c86073a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=True),
    sa.Column('draft_type', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drafts_company_id'), 'drafts', ['company_id'], unique=False)
    op.create_index(op.f('ix_drafts_contact_id'), 'drafts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_drafts_organization_id'), 'drafts', ['organization_id'], unique=False)
    op.add_column('outreach_activities', sa.Column('draft_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'outreach_activities', 'drafts', ['draft_id'], ['id'])
    op.add_column(
        'role_categories',
        sa.Column(
            'framing_style', sa.String(length=20), nullable=False, server_default='business'
        ),
    )
    op.alter_column('role_categories', 'framing_style', server_default=None)
    op.add_column('role_relevance_results', sa.Column('matched_category_framing_style', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_relevance_results', 'matched_category_framing_style')
    op.drop_column('role_categories', 'framing_style')
    op.drop_constraint(None, 'outreach_activities', type_='foreignkey')
    op.drop_column('outreach_activities', 'draft_id')
    op.drop_index(op.f('ix_drafts_organization_id'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_contact_id'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_company_id'), table_name='drafts')
    op.drop_table('drafts')
    # ### end Alembic commands ###
