"""add contact timezone and outreach activities table

Revision ID: 73bd7c86073a
Revises: b7d453221122
Create Date: 2026-09-11 16:49:28.335526

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '73bd7c86073a'
down_revision: str | None = 'b7d453221122'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('activity_type', sa.String(length=30), nullable=False),
    sa.Column('template_variant', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_activities_contact_id'), 'outreach_activities', ['contact_id'], unique=False)
    op.create_index(op.f('ix_outreach_activities_occurred_at'), 'outreach_activities', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_outreach_activities_organization_id'), 'outreach_activities', ['organization_id'], unique=False)
    op.add_column('contacts', sa.Column('timezone', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'timezone')
    op.drop_index(op.f('ix_outreach_activities_organization_id'), table_name='outreach_activities')
    op.drop_index(op.f('ix_outreach_activities_occurred_at'), table_name='outreach_activities')
    op.drop_index(op.f('ix_outreach_activities_contact_id'), table_name='outreach_activities')
    op.drop_table('outreach_activities')
    # ### end Alembic commands ###
