"""add qualification_criteria table

Revision ID: 9cdaed069372
Revises: 0006
Create Date: 2026-09-10 18:27:35.453737

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '9cdaed069372'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also detected pre-existing drift on `users` (an old unique-constraint
    # vs. unique-index mismatch, unrelated to this change) — deliberately left out of this
    # migration; out of scope for the qualification criteria catalog.
    op.create_table('qualification_criteria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_disqualifying', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualification_criteria_organization_id'), 'qualification_criteria', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qualification_criteria_organization_id'), table_name='qualification_criteria')
    op.drop_table('qualification_criteria')
    # ### end Alembic commands ###
