"""add role_categories and role_relevance_results tables

Revision ID: b7d453221122
Revises: d8fbdc0aca73
Create Date: 2026-09-11 02:13:57.941794

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b7d453221122'
down_revision: str | None = 'd8fbdc0aca73'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_primary_target', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_categories_organization_id'), 'role_categories', ['organization_id'], unique=False)
    op.create_table('role_relevance_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('matched_category_id', sa.Uuid(), nullable=True),
    sa.Column('matched_category_name', sa.String(length=255), nullable=True),
    sa.Column('is_primary_target', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('reasoning', sa.String(), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['matched_category_id'], ['role_categories.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_relevance_results_company_id'), 'role_relevance_results', ['company_id'], unique=False)
    op.create_index(op.f('ix_role_relevance_results_contact_id'), 'role_relevance_results', ['contact_id'], unique=False)
    op.create_index(op.f('ix_role_relevance_results_organization_id'), 'role_relevance_results', ['organization_id'], unique=False)
    # ### end Alembic commands ###
    # (autogenerate also picked up unrelated pre-existing `users` table drift — a
    # unique-constraint vs. unique-index mismatch seen on every migration so far — stripped here,
    # out of scope for this change.)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_relevance_results_organization_id'), table_name='role_relevance_results')
    op.drop_index(op.f('ix_role_relevance_results_contact_id'), table_name='role_relevance_results')
    op.drop_index(op.f('ix_role_relevance_results_company_id'), table_name='role_relevance_results')
    op.drop_table('role_relevance_results')
    op.drop_index(op.f('ix_role_categories_organization_id'), table_name='role_categories')
    op.drop_table('role_categories')
    # ### end Alembic commands ###
